### ISSUE TITLE
Wrong culture

### ISSUE THREAD

**Issue by plemay** [Ethck/azgaar-foundry#10]
Hi,

In the notes, you always show the next culture Id instead of the right culture.

So If the city have the X Culture, in the notes you link and show the X+1 culture.

/***
Foundry VTT 0.8.9
Dnd5e 1.5.5
Azgaar 0.2.2
****/

Thx, very nice plugins

**Comment by Ethck** [comment]
Huh, that's interesting! I thought for sure I had accounted for such things, but I'll test, review, and make a fix for this. Thanks for the report!
