### ISSUE TITLE
Failure to Complete 

### ISSUE THREAD

**Issue by Mingus-Analingus** [Ethck/azgaar-foundry#12]
![Example](https://i.imgur.com/C6sfqoU.png)
On foundry 8.8 linux, Libwrapper and Pin-Fixer likewise:
Uploading map file and map image work fine, however it throws this error after making the journal entries and the scene,  but does not place the pins on the map.  Likewise the module setup window becomes impossible to close but does not hard-lock the software.  Rebooting the world and or program leaves what it has already placed but aborts the process.

**Comment by Ethck** [comment]
It seems as if the parsing of the map file is somehow messed up. Can you attach the map file in question? Looks like it should be something along the lines of `Pia 202021-12-21-16-12.map`.

**Comment by Mingus-Analingus** [comment]
https://www.dropbox.com/s/v4qnvhspz2ryv2y/Pia%202021-12-21-16-06.map?dl=0
Here you go.

**Comment by Ethck** [comment]
There was an issue with a province that had been removed in the map editor, but it still showed up in the data. This has been corrected with de33de5. New release incoming.
