### ISSUE TITLE
Resolution and Pins

### ISSUE THREAD

**Issue by mudgw2** [Ethck/azgaar-foundry#13]
Greetings! awesome mod...very happy to use it for an upcoming game.  I have two questions to understand the limitations of the tool:
* How can I get the highest resolution..I export SVG (which should not de rez) and import it into Foundry and it gets fuzzy.. I tried scaling and setting resolutions but whats needed for a sharp 4k image (and I assume SVG is being converted in Foundry to raster...)
* I dont see any of the towns, despite zomming in and out...could the pins not be working currently?
Thanks!

**Comment by Ethck** [comment]
The pins should absolutely be working! Double check on the left hand side on the Journal Notes button that you're either on that layer or have selected the Magnifying glass to see it on other layers. If that still doesn't seem to work, let me know. Another question, do you see ANY pins, or is it just the towns that are missing (in other words, do you see the countries & provinces?)

I have no idea how to get the highest resolution, but I will spend some time today to develop a method for ensuring high quality images.

**Comment by mudgw2** [comment]
![image](https://user-images.githubusercontent.com/2263938/152229429-e3086a93-d07c-4a26-addd-ac5782ea859a.png)

I think I selected pins correctly but still dont see them...Journal is also blank...

Im kinda new to Foundry so maybe I'm doing something wrong.

**Comment by Ethck** [comment]
This is a map that I imported today (also generated today) using the current version of the module and most recent version of Foundry. I exported the SVG from azgaar and set the internal scaling (through the module dialog) to 10x which resulted in a background that is 18270x9780.
![image](https://user-images.githubusercontent.com/44616794/152221747-4c4ded01-3e74-472b-8cff-faec28602434.png)

It seems like there is some extra blurriness, so I'm working on a solution to that.

**Comment by Ethck** [comment]
So all of the information pertaining to your world will actually be in some compendiums that were created for your world. They will be named things like "Provinces", "Countries", "Burgs", etc. You are indeed in the right area, weird that they're not showing up. Was there an error on creating them? You'd have to check the console with f12 and look for any red text.

**Comment by mudgw2** [comment]
Ah compendiums..didnt think to look there..I will give that a look! thanks. If I get red errors in the console I will report here.

**Comment by Ethck** [comment]
For some reason SVGs are extremely blurry. My suggestion is to load a PNG or JPEG file of the appropriate scale.
