### ISSUE TITLE
Quality of Life

### ISSUE THREAD

**Issue by NewDaedalus** [Ethck/azgaar-foundry#15]
I do encounter an issue where Provinces with no under lying Burgs don't produce pins, and creating pins for them then creates a journal entry which is separate to the compendium entry, and both can be edited independently with no way (that I have found) to easily identify between the 2 to ensure integrity of information added/saved.

but I wanted to suggest some what I think (I haven't looked at code in 12 years) should be simple additions that would make navigating through so much more intuitive just by editing the templates.

suggested edits below 

burgs

>     <h4>State: @Compendium[world.Countries.{{iter.country.journal.id}}]</h4>
>     <h4>Province:` @Compendium[world.Provinces.{{iter.provinces.journal.id}}]</h4>
>     <h4>Culture: @Compendium[world.Cultures.{{iter.culture.journal.id}}]</h4>

Province 

>     <h4>Full Name: {{iter.fullName}}</h4>
>     <h4>State: @Compendium[world.Countries.{{iter.country.journal.id}}]</h4>
>     <details>
>         <summary>Burgs</summary>
>         <ul>
>             {{#each iter.selBurgs}}
>                 <li><span>@Compendium[world.Burgs.{{this.journal.id}}]</span></li>
>             {{/each}}
>         </ul>
>     </details>
>     <h4><b>Color: </b>

I don't know if it would be that simple their might be some changes needed to the way the data is stored/retrieved was just something I noticed might be a nice win for anyone else starting a new setting/continent  

I otherwise love this module its saved me unfathomable amounts of time and has made importing a map super simple

**Comment by Ethck** [comment]
Thank you for the suggestions! I will take a look and likely incorporate this in the next release.

**Comment by Ethck** [comment]
So while it would indeed be nice to add the province to the burg list, it doesn't seem feasible at the moment. Here is the data associated with a burg:
`burgURL: "[http://fantasycities.watabou.ru/?random=0&continuous=0&name=…01&coast=NaN&citadel=0&plaza=1&temple=1&walls=0&shantytown=0](http://fantasycities.watabou.ru/?random=0&continuous=0&name=Baklos&population=21249&size=NaN&seed=831487950201&coast=NaN&citadel=0&plaza=1&temple=1&walls=0&shantytown=0)"
​​​
capital: false
​​​
cell: 6870
​​​
citadel: 0
​​​
coa: Object { t1: "sable", charges: (1) […], shield: "spanish" }
​​​
country: Object { id: 2, name: "Kispokia", journal: {…} }
​​​
culture: Object { id: 7, name: "Hithes", journal: {…} }
​​​
feature: 31
​​​
i: 201
​​​
name: "Baklos"
​​​
plaza: 1
​​​
population: 21.249
​​​
port: 0
​​​
shanty: 0
​​​
state: 2
​​​
temple: 1
​​​
type: "Generic"
​​​
walls: 0
​​​
x: 800.91
​​​
y: 859.98`

**Comment by Ethck** [comment]
However, it does seem as though provinces list their burgs... I'll see if I can work something out.
