### ISSUE TITLE
Compatibility with Monks Enhanced Journal 

### ISSUE THREAD

**Issue by QuantumBob** [Ethck/azgaar-foundry#16]
First, great work.
Is there a way to make the importer compatible with Monks Enhanced journals? Whenever it is activated the only journal that appears is the first country in the .map file, and there is libWrapper conflict about Monks not chaining the clickleft2 function. If I stick a breakpoint in the importers clickleft2 function it doesn't get hit. 
Hope this makes sense. It's not a bug but a feature request!

**Comment by mlautensack** [comment]
This might also pull off the future plan of "Better way to display the data" as Monk's Place Journals have details panel that include Government, Inhabitants, Agriculture, Culture, Education, Industry, Mercantile, and Military descriptions as well as a relationships tab that can link locations via their relationship.

**Comment by PsykotikDragon** [comment]
> First, great work. Is there a way to make the importer compatible with Monks Enhanced journals? Whenever it is activated the only journal that appears is the first country in the .map file, and there is libWrapper conflict about Monks not chaining the clickleft2 function. If I stick a breakpoint in the importers clickleft2 function it doesn't get hit. Hope this makes sense. It's not a bug but a feature request!

I am also having this same issue & was hoping to find a solution here but it seems I'm not the only one.

**Comment by Ethck** [comment]
Is there interest in this after the v10 update?

**Comment by PsykotikDragon** [comment]
> Is there interest in this after the v10 update?

I've been using this since before I started our foundry server, back when we were using Roll20 still, & continue to use this. Would love to see this updated to v10 & functioning, especially with MEJ.

**Comment by Ethck** [comment]
To be clear, @PsykotikDragon there is a V10 version with a couple more features! Can you give that a whirl and see if MEJ support is still necessary?

**Comment by PsykotikDragon** [comment]
> To be clear, @PsykotikDragon there is a V10 version with a couple more features! Can you give that a whirl and see if MEJ support is still necessary?

getting this error with everything updated to the newest version.
![image](https://user-images.githubusercontent.com/52022617/198445111-9c6fba99-4abb-40db-87c6-1b97cdae42d7.png)

**Comment by Ethck** [comment]
Hmm... I'll see if I can't get them to play nice.

**Comment by Ethck** [comment]
@PsykotikDragon if you have issues with the import process, please open another issue with descriptions of what's happening. For example, is there a red error message that pops up? Are the compendiums generated? etc.

**Comment by PsykotikDragon** [comment]
> @PsykotikDragon if you have issues with the import process, please open another issue with descriptions of what's happening. For example, is there a red error message that pops up? Are the compendiums generated? etc.

Only mentioned it here bc I only just now discovered it & I thought it might've been connected to the existing issue
