### ISSUE TITLE
Links to watabou...

### ISSUE THREAD

**Issue by tmexx** [Ethck/azgaar-foundry#18]
Within the website, links at the burg level to watabou's city generator seem to pass through the "layout" of adjacent water bodies etc.

Once the map is imported to Foundry, the city names pass through to City Generator but the "layout" does not.

Fixable?

**Comment by DeimosJ** [comment]
Comparing two generated links from FMG and this module it seems like not only has the City Generator data changed but also the site that is used to generate a city.

As you can see below, the link generated by FMG uses the github.io version of the generator (part of Watabou's Procgen Arcana project) where as this module is using fantasycities.watabou.ru which appears to be an older version of the project.
FMG also seems to use some sort of calculation to decide on the size of the map as well as the sea value, this data isn't stored in the .map file.

Link from Azgaar's FMG: https://watabou.github.io/city-generator/?size=37&seed=5629980290003&name=Bellstar&population=16596&greens=0&farms=1&citadel=1&urban_castle=0&plaza=1&temple=1&walls=1&shantytown=0&coast=1&river=1&gates=-1&sea=1.91

Link from Foundry VTT: http://fantasycities.watabou.ru/?size=15&seed=5629980290003&name=Bellstar&population=16596&hub=0&random=0&elevation=1&green=0&farms=1&citadel=1&urban_castle=0&plaza=1&temple=1&walls=1&shantytown=0&river=1&coast=1&sea=0.7909468285697264

Perhaps it would be easier to ask if Azgaar can add the generated URL to the .map file then to try and emulate his process?

**Comment by Ethck** [comment]
Thank you for this extensive analysis! This should be a relatively simple fix, and I will get to it soon. I've been on a bit of a break, but this is perfect to get back into the swing of things.

**Comment by Matt-Int** [comment]
I've also had similar issues where the url in the journal has `NaN`s in them instead of a 1 or 0, this is leading to cities in the middle of a landmass to have a port in some cases and a coastal city to have no port at all, see the example link below.

`http://fantasycities.watabou.ru/?random=0&continuous=0&name=Guigne&population=1454&size=NaN&seed=13477316070091&coast=NaN&citadel=1&plaza=1&temple=0&walls=1&shantytown=0`

I think this might be caused in the following function where `${+burg.coast}` etc. evaluates to `NaN`. At least that's my best guess!

https://github.com/Ethck/azgaar-foundry/blob/894ac8f61285b272a2d04c0961756e7538bee109/main.js#L421-L429

**Comment by PsykotikDragon** [comment]
> Comparing two generated links from FMG and this module it seems like not only has the City Generator data changed but also the site that is used to generate a city.
> 
> As you can see below, the link generated by FMG uses the github.io version of the generator (part of Watabou's Procgen Arcana project) where as this module is using fantasycities.watabou.ru which appears to be an older version of the project. FMG also seems to use some sort of calculation to decide on the size of the map as well as the sea value, this data isn't stored in the .map file.
> 
> Link from Azgaar's FMG: https://watabou.github.io/city-generator/?size=37&seed=5629980290003&name=Bellstar&population=16596&greens=0&farms=1&citadel=1&urban_castle=0&plaza=1&temple=1&walls=1&shantytown=0&coast=1&river=1&gates=-1&sea=1.91
> 
> Link from Foundry VTT: http://fantasycities.watabou.ru/?size=15&seed=5629980290003&name=Bellstar&population=16596&hub=0&random=0&elevation=1&green=0&farms=1&citadel=1&urban_castle=0&plaza=1&temple=1&walls=1&shantytown=0&river=1&coast=1&sea=0.7909468285697264
> 
> Perhaps it would be easier to ask if Azgaar can add the generated URL to the .map file then to try and emulate his process?

is there a way to manually change that link to use the correct one in the foundry module? or somewhere in the data where you found the older version's link?
