### ISSUE TITLE
Mapping of .map data to journal entries is incorrect

### ISSUE THREAD

**Issue by DeimosJ** [Ethck/azgaar-foundry#20]
I've noticed that the data within the .map file isn't accurately mapping to journal data correctly, As per the below image, the burg Bellstar lists its province as Flarereva however it is in the Province of Bellstar County.

![Incorrect Data](https://user-images.githubusercontent.com/70048990/181935732-6ba0787a-c088-4f5b-82be-d4081065313b.PNG)

I've looked through the .map file and the Bellstar burg index is in the list of province indices for Bellstar County and not in Flarereva's list.

Unofficial Azgaar's Fantasy Map Generator Import version: 0.2.8
FMG version: 1.8 (current stable version used [here](https://azgaar.github.io/Fantasy-Map-Generator))
Foundry Version: 9.269

**Comment by Ethck** [comment]
Can you link the map file you are using?

**Comment by DeimosJ** [comment]
Sure thing.
[Here you go.](https://drive.google.com/file/d/1aGwSjk1dVg-ceXSjvpzCNGSgVAyG0p_V/view?usp=sharing)

**Comment by SirNiloc** [comment]
Mine does the same
