### ISSUE TITLE
Update for Foundry v10 Stable?

### ISSUE THREAD

**Issue by soryy708** [Ethck/azgaar-foundry#23]
Foundry VTT released Version 10 in the Stable branchon August 31, 2022.
Any plans to make this module work with v10?

**Comment by Ethck** [comment]
Yes! I have a local branch where I'm currently trying to make it compatible, and hopefully fixing any new bugs, while also adding some additional features since the journal overhaul happened in v10.

**Comment by soryy708** [comment]
What is the scope of needed work here? Maybe the community can help if the backlog is made public?

**Comment by Ethck** [comment]
The conversion to be "operable" in v10 is done, but I'm trying to design a better journal solution. I'll probably end up making a release tomorrow with what I have so that it at least works in v10.

**Comment by xxUltiMoxx** [comment]
I would love to see an update for v10 as well, so keep up the good work!

**Comment by Ethck** [comment]
My apologies... I got caught up with some IRL stuff, but I have now released a v10 compatible version! Enjoy!
