### ISSUE TITLE
Potential bug (v10): not filling journey entries correctly and not placing province pins on scene.

### ISSUE THREAD

**Issue by Subwoof01** [Ethck/azgaar-foundry#28]
### Version info
FoundryVTT version: v10 (build 286)
Azgaar's version: 1.87.13
Module version: 0.3.1

### Problem
When importing a map into Foundry, the module generates all the journey entries correctly (all the provinces and burgs are listed in their respective compenia), however the links inside the journal entries are oftentimes missing. It also doesn't seem to place the province pins on the scene.

The missing journey entry links are as such:
#### Burgs
![image](https://user-images.githubusercontent.com/20887751/193040443-fb368ba4-4a82-4cb6-9300-045b4a4fe5ca.png)

#### Provinces
![image](https://user-images.githubusercontent.com/20887751/193040616-5d67eed8-58b4-4ff2-bfd0-92f6fd19ccf8.png)
(The dropdown of burgs inside the province is empty).

### Tried solutions
I have tried regenerating things in Azgaar's map maker in both orders (regenerate state->provinces->burgs and burgs->provinces->states) thinking it might be due to it assigning which province a burgh belongs to on generation. This had no effect.

If you require me to add additional info, do tell. I will do what I can to provide it.

**Comment by xxUltiMoxx** [comment]
For me the importer throws an exception while importing provinces and crashes. 
I will deliver a screenshot in the near future...

**Comment by xxUltiMoxx** [comment]
![image](https://user-images.githubusercontent.com/22027445/193941169-3b3c20dc-61b6-4641-ae45-d8b6a90a359d.png)

**Comment by xxUltiMoxx** [comment]
alright, after some testing i can confirm that provinces are not linked properly... in the provinces entries the states and burgs entries are empty or not linked. 
Furthermore, the importer is mixing up cultures. 
For Example: My Human Culture that is shown as Human in Azgaar, is linked and shown as Dwarish after the Foundry import, my dwarfish culture is shown orkish and so on...

**Comment by Ethck** [comment]
Solving the Culture error in #32

**Comment by Ethck** [comment]
Closed with commit 44f829b
