### ISSUE TITLE
Import button unclickable when using Massive PNG

### ISSUE THREAD

**Issue by aramyle** [Ethck/azgaar-foundry#33]
I have the .map file and the .png file chosen. The import button doesn't light up to click. If I change the png to another image it will work, but of course that's not what I want.

**Comment by Ethck** [comment]
That's odd. I don't intentionally disable the import button. Can you attach the map file and picture here and I can try?

**Comment by aramyle** [comment]
PNG: https://drive.google.com/file/d/1k_hl1V6q7bulXXr7Gbf7M-M0MB-DI1ky/view?usp=sharing
MAP: https://drive.google.com/file/d/1zGS97bMCJOq_G_MvQ1lELksNR9MtIBAn/view?usp=sharing

**Comment by Ethck** [comment]
I think that PNG is too big since it's 20480 x 11064. I was able to load the map file and it worked, but WebGL can't seem to render that image. Try using a smaller size.
