### ISSUE TITLE
Black Map With No Pins

### ISSUE THREAD

**Issue by Cavemanuni** [Ethck/azgaar-foundry#38]
I have just done a first time install of the module(v 0.3.3) and of Pin Fixer(v 1.2.2). I followed the instructions and uploaded a .map and its respective .png file. It worked as it seemed it should however I didnt see any pins however I had also noticed that i had the labels visible on the png file and so deleted it as a scene and went back through the settings to import a new one. This time it showed nothing but black. Thought i had missed something so i redid it and same thing. Reset foundry, same thing. ReSaved and imported the .map, same thing. Uninstalled and reinstalled both this module and Pin Fixer and saved and exported the map again, still showing nothing but black. Did i break something deeper into the files? All of the rest of my scenes still work fine to not much supprise.

**Comment by Ethck** [comment]
Try ensuring that the scale you set on the map is not above what your GPU can handle. If you're setting the scale to 1 and you still encounter this problem, be sure to let me know. This is a limitation of WebGL where you can only render textures of a certain size, and it's very difficult to render an image of size 20480x11440, for example.
