### ISSUE TITLE
MINOR BUG - Error: Required field "name" not present in SceneData

### ISSUE THREAD

**Issue by p4535992** [Ethck/azgaar-foundry#4]
**Environment Details**

Foundry VTT Version: 0.8.9

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.4.2

Modules Enabled?: Yes (if you need i can give you the full list)

Module version: 0.2.1

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

Ater load the ".map" file ad hit the button "Import" i get this error:

![img](https://i.imgur.com/D9Pkj3s.png)

it's because i forgot to set a image for the "Link to picture" module setting, after that the panel form is broke, so for now the solution is a simplerefresh.

A solution can be to add a mandatory validation for that field.

**Comment by Ethck** [comment]
Ah, interesting! That is at least a simple fix. I haven't gotten back around to this module since the package jam, but will be prepping an update soon that will include this fix.
