### ISSUE TITLE
Install not Working

### ISSUE THREAD

**Issue by Arcane-Scholar** [Ethck/azgaar-foundry#40]
Trying to install in Foundry 11 Build 308 using https://github.com/Ethck/azgaar-foundry/blob/master/module.json and I get an error about a "Module validation error: id may not be undefined."

**Comment by Ethck** [comment]
You should be able to install directly from the foundry browser, if not please use https://github.com/Ethck/azgaar-foundry/releases/latest/download/module.json as the module.json link as that will grab the appropriate version.
