### ISSUE TITLE
City "size" left off, resulting in broken links

### ISSUE THREAD

**Issue by dirkson** [Ethck/azgaar-foundry#42]
When importing a map, the importer appears to trim the 'size' attribute out of cities and towns, which breaks the links it creates to watabou's city generator. This attribute seems to be present in the links Azgaar itself provides.

**Comment by AlexFauteux** [comment]
I would add also that the population size also seems to be trimmed to some degree as well. I have a city with 29 000 people but in the import it has 29.

**Comment by Ethck** [comment]
Fixed as of today.
