### ISSUE TITLE
Incompatible with version 12

### ISSUE THREAD

**Issue by GoosePeelings** [Ethck/azgaar-foundry#43]
Hopefully this module gets updated. 
I just managed to port a map to Foundry before updating it and now the module cannot be enabled anymore.

**Comment by Ethck** [comment]
Thanks for letting me know, I had set a maximum version for version 11 in the manifest, but as it turns out the module is broken in v12. I'm in the middle of a rewrite currently with a bunch of awesome updates and should hopefully get this out in the next week with working v12!

**Comment by SaturnVStar** [comment]
Any Update on the v12 upgrade?

**Comment by Ethck** [comment]
Real life unfortunately got very busy. The rewrite is in progress still, and I'm taking another stab at it this morning.

**Comment by Ethck** [comment]
Should be solved by #44 . Just released a new version.
