### ISSUE TITLE
While importing I get this

### ISSUE THREAD

**Issue by BadBlackLion** [Ethck/azgaar-foundry#45]
I am on the newest release (12.330) of Foundry and on your module as well. When I try to import my created world I get the following:
![FMG-Importer-Fehler](https://github.com/user-attachments/assets/52d4280b-4909-42ee-94ac-96621da009d0)
![FMG-Importer-Fehler-02](https://github.com/user-attachments/assets/b56d2e03-5afa-43c0-a176-a09209459130)
![FMG-Importer-Fehler-03](https://github.com/user-attachments/assets/fa4b9dcc-6bd8-4ca7-8ddd-193e0c1bbb3d)
I followed your instructions here and still don't know what exactly went wrong.
I tried it while running Foundry as admin as well and still got this.
Is it normal for the journal to be empty and the file name to be put as scene name?
I'd really love to use your importer, because it saves a lot of time, if it works.

Yours

**Comment by Ethck** [comment]
Looks like there was an issue with the markers. Can you link your map file (full json preferred). Journals are available in the compendium tab and you can see the scene notes by clicking on the banner icon on the left. You can then hit the magnifying glass icon to toggle the ability to see notes outside of the notes view.

**Comment by BadBlackLion** [comment]
Here you can find my [.json-File](https://drive.google.com/file/d/15HXzS4CwtLI8Ey3o1BS5wmUxwIvzg340/view?usp=sharing).

**Comment by MatthewRnelson-ECS** [comment]
I just wanted to comment that I had the exact same issue. I also noticed that the marker compendium that is brought in seems to be blank. Maybe something has happened with the icons and it is throwing an error because it doesn't have anything to grab to bring in?

**Comment by Ethck** [comment]
Finally got around to finding and fixing this issue, it was pretty troublesome to find. Statues that get imported usually have text in different languages and some of the characters used apparently can't be rendered properly inside of Foundry for some reason.
