### ISSUE TITLE
Imformation import wrong

### ISSUE THREAD

**Issue by Dragonzofdeath** [Ethck/azgaar-foundry#47]
I went threw adjusting every city to my liking and fixing every city and religion how i wanted it... i don't know if it's pulling from memory but every-time i hit import it import either A the default information or B an old information i had when i first was learning to install the system i have gone and individually deleted every compendium ... now i would say maybe something wrong but i added a new city and it still only import the default setting which i know i never upload a previous city now i have to fix the journal of 400 cities and so many religions have to be fix to match what i have.... now i know the json files has the correction information cause i double and triple checked

**Comment by Dragonzofdeath** [comment]
![error](https://github.com/user-attachments/assets/ebb16137-d4b1-4e07-bdf5-eb77c0e0559e)

**Comment by Arenndumi** [comment]
you delete the 'Azgaar FMG' in the Journal?

**Comment by Dragonzofdeath** [comment]
yes then i readded the information and it added the default maps not the updated ones... everythign i tried i couldn't added the updated maps unless if i did it manually  i even deleted every compendium

**Comment by Ethck** [comment]
@Dragonzofdeath can you include the current `.map` file, a picture showing what is wrong, and a picture of what it should be? Based on what I'm seeing above it looks like the link to MFCG is wrong?

**Comment by Dragonzofdeath** [comment]
basically when i import json it's not importing the link it's creating a new link... without posting multiple imagines it hard to show but i'll try my best

**Comment by Dragonzofdeath** [comment]
![{36BB9B7D-830C-4AC6-AEDC-A63DF7F2E432}](https://github.com/user-attachments/assets/c6bcb9c2-938f-4616-8623-367b524e3264)
json file how it look to show the code... link is seed 6536853930253 with 2 gates

**Comment by Dragonzofdeath** [comment]
![{35B60F62-3C9F-4C55-9D8E-383166EF12DE}](https://github.com/user-attachments/assets/8011a1a1-d83e-40e1-b2f2-cff7cad0caf6)
as you can see the seed being imported is completely diffen't

**Comment by Dragonzofdeath** [comment]
![{CC52C325-3FF8-4C23-A02D-CBCFA5899508}](https://github.com/user-attachments/assets/b36e9ff4-b1f4-44af-948e-05398ec60ebf)
as you can see this has -1 gate some of them have competely diffenr't seeds.. cause i had to change them

**Comment by Dragonzofdeath** [comment]
![{1DD1524C-261D-42AF-817B-979683667DCD}](https://github.com/user-attachments/assets/b8c53b86-9c4c-4d93-89bf-7bfbc6827cb7)
![{B2468B45-6630-439B-ACD3-E41B08C0CEBE}](https://github.com/user-attachments/assets/0e51d8e8-f1ac-4263-be23-5e7d9f22f11a)
here another one sea level different and gates are different which changes the happen majorly

**Comment by Dragonzofdeath** [comment]
![{E07AD8C9-67A6-494B-9F50-CA80B716ECC0}](https://github.com/user-attachments/assets/56c1969e-110e-4e23-b75f-73878471ffec)
![{199FED8B-731C-4A39-A3F0-ED619250ED3A}](https://github.com/user-attachments/assets/cdf9a2b9-de27-4d66-9ba4-d730bd0fe588)
what got imported is 
https://watabou.github.io/city-generator/?name=Adhishali&population=16508&size=37&seed=6536853930042&river=0&coast=1&farms=1&citadel=0&urban_castle=0&hub=false&plaza=1&temple=0&walls=1&shantytown=0&gates=2&sea=0.09 
what i have in azgaar is
https://watabou.github.io/city-generator/?name=Adhishali&population=16508&size=37&seed=6536853930042&river=1&coast=1&farms=1&citadel=0&urban_castle=0&hub=true&plaza=1&temple=0&walls=1&shantytown=0&gates=2&sea=1.89

this kinda error is on all on all my burgs and i have to fix close to 500 burgs

**Comment by Dragonzofdeath** [comment]
![{3A7484EB-B3F7-4382-BDAD-0AE3154F97F8}](https://github.com/user-attachments/assets/d8da5d96-1bda-42b6-bf86-ec22e83294bb)
![{64264B56-9140-4FB4-B8C1-9C9A408B3BF1}](https://github.com/user-attachments/assets/b2ca7689-928c-4452-97f2-ce915bd6bc59)
what get imported to foundry is 
https://watabou.github.io/city-generator/?name=Adhishali&population=16508&size=37&seed=6536853930042&river=0&coast=1&farms=1&citadel=0&urban_castle=0&hub=false&plaza=1&temple=0&walls=1&shantytown=0&gates=-1&sea=0.09
what is entered in Azgaar
https://watabou.github.io/city-generator/?name=Adhishali&population=16508&size=37&seed=6536853930042&river=1&coast=1&farms=1&citadel=0&urban_castle=0&hub=true&plaza=1&temple=0&walls=1&shantytown=0&gates=2&sea=1.89

small little differn't that majorly effect maps

**Comment by Dragonzofdeath** [comment]
![{E8CABBF4-4061-46AC-87D3-44B34FE31B0C}](https://github.com/user-attachments/assets/60c3f805-d87b-41e5-af37-b7fd3a630c08)
![{66504286-3FDB-4618-A611-8D22997D64F4}](https://github.com/user-attachments/assets/766089c9-9da3-4a11-86fe-aeb64f6ac286)
milara is completely differn't not even the correct seen name ... i hope this helps

**Comment by Dragonzofdeath** [comment]
![{913623D2-CB48-428F-A2DE-D7EDA45ED0D8}](https://github.com/user-attachments/assets/ca2eb3a6-6f59-41a3-8bb3-c95c959683bf)
this one actually even gives me 2 differn't generators one is village generator other is city generator

**Comment by Ethck** [comment]
Thank you for the info! I'll try to figure out what's going on and get a fix out for this.
