### ISSUE TITLE
Compendium error on Import

### ISSUE THREAD

**Issue by FernandoSAguiarNeto** [Ethck/azgaar-foundry#49]
Hello, when I try to import I receive the following error:

![image](https://github.com/user-attachments/assets/a2135bec-6555-4f89-b01b-d539955f3823)

My foundry is at v12.331 and the module is up-to-date (v0.5.1). I made two different files with different configs and both give the same error.

[smaller.zip](https://github.com/user-attachments/files/17452409/smaller.zip)
[fabula-teste.zip](https://github.com/user-attachments/files/17452410/fabula-teste.zip)

Is it local or some bug, is there anything I can provide for replication/help?

Thanks in advance

**Comment by Ethck** [comment]
This is a very strange error, but my hunch is that it's related to the new
multi-world compendiums. For now try turning off that option. I'll
investigate this error tomorrow.

**Comment by FernandoSAguiarNeto** [comment]
Hello, thanks for the fast response. I tried with the option "Use world specific compendium" both on and off and the error persisted.
Take your time to investigate, I will try a few things.

A friend of mine removed all parenthesys in 'names' and also single-quotes from the json and aparently it worked fine. Perhaps is something in the name generation of new compendiums.

**Comment by Ethck** [comment]
I can't seem to replicate the issue with import failure on names, but the "fabula-teste.zip" map full json does cause several issues with the module that I'm working through to fix.

**Comment by Ethck** [comment]
Scratch that, the other errors were preventing me from seeing it. The issue here is likely to do with the spaces so I'll add some code to get around that.

**Comment by Ethck** [comment]
Should be fixed now! I just published the release as well so should be all set.

**Comment by FernandoSAguiarNeto** [comment]
Thank you! o/
