### ISSUE TITLE
Error after making map. No pins appear. Compendium for burgs doesnt exist.

### ISSUE THREAD

**Issue by CatbotTsumi** [Ethck/azgaar-foundry#6]
Something went wrong here. I followed instructions. This is the stuff I used:
.map file: https://drive.google.com/file/d/1lKuZ1Tm-W0rXd0TMFmNLSyvuuIJTjFra/view?usp=drivesdk
Link to Picture: https://drive.google.com/file/d/1X-Tg3kBXwywFLFH7N0ZaOVfW_ssM8zqw/view?usp=sharing
Scale Factor 5 (didn't match up so I adjusted the X/Ysize to 12800x6360 manually)
Changed 3 icons for burgs, countries, and provinces.
Left MapNote scaling on default.
Pressed Import.

Here's what I got. I got a new scene with the linked picture, but no pins (made sure i have them visible). 
The following compendiums were created: Cultures, Provinces. (No burgs??)

And looking in the Console I got:

```js
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: azgaar-foundry]
    at Function.keys (<anonymous>)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:8657)
    at async ClientDatabaseBackend._createDocuments (foundry.js:8603)
    at async Function.createDocuments (document.mjs:332)
    at async compendiumUpdater (main.js:530)
    at async http:/localhost:6969/modules/azgaar-foundry/main.js:232```

**Comment by Ethck** [comment]
Hello! Thank you for this report. I will be looking into it today. One additional question, how old is this map file? Is it something you have been working on for years or just within the past couple of months/weeks? This is important so I can ensure that this isn't a migration error.

**Comment by Ethck** [comment]
Ah, I notice now that this is because the data for the countries is still present, even though they have been removed (highlighted by their data containing the `removed: true` property. I am currently testing a fix for this and should have it out shortly.

**Comment by CatbotTsumi** [comment]
This map has been made like most 2 weeks ago.

Lots of love,
Tsumi

**Comment by CatbotTsumi** [comment]
Any updates on this?

**Comment by Ethck** [comment]
Hey sorry about the delay on this. I have something that sort of works locally but I'm still trying to work out all of the bugs with it (turns out there were quite a few). I'll try to get something out this weekend.
