### ISSUE TITLE
[0.8.8] Error on map import

### ISSUE THREAD

**Issue by Shadowerie** [Ethck/azgaar-foundry#7]
Just cant seem to get he module to work when I submitted the .map file and then .png image, once I start the3 process the pop out wont close either
[Malnoa 2021-09-22-13-54 - Copy.zip](https://github.com/Ethck/azgaar-foundry/files/7212932/Malnoa.2021-09-22-13-54.-.Copy.zip)
.

**Comment by Ethck** [comment]
Seems to have the same "removed": "true" property as #6 . Hoping it's the same bug. Should be able to find time this weekend to release an update.
