### ISSUE TITLE
Notes won't appear

### ISSUE THREAD

**Issue by ADDrathin** [Ethck/azgaar-foundry#9]
I don't know what I'm doing wrong or if it is a bug. I cannot for the life of me get the notes to appear on the map in foundry. Like the .map data isn't showing.

**Comment by Ethck** [comment]
My apologies for only just now noticing this. There are a couple of possible issues. The first is that you are not showing notes. The Notes layer is this banner looking picture (highlighted in photo) 
![image](https://user-images.githubusercontent.com/44616794/142045955-8b8b9676-67cd-4b76-bdaa-0149645880a9.png)
The magnifying glass will toggle whether or not you can see notes when outside of the notes layer.

This is assuming that everything works of course. If the above does not solve your issue then it is likely that there is a bug in the program. Please let me know what system you are using (and the version!), the version of this module, and please include the map file. These details will help me figure out why there might be an error.

**Comment by ADDrathin** [comment]
I am running Windows 10. The module version is 0.2.2.

**Comment by ADDrathin** [comment]
I was unable to attach the .map file.

**Comment by Ethck** [comment]
Apologies, when I meant system I meant which game system are you using. Are you using D&D5e, Pathfinder 1/2, Simple Wordbuilding, etc. ?

**Comment by ADDrathin** [comment]
D&D 5e
